feat: test validator

diff --git a/service-build/spark-build/action.yaml b/service-build/spark-build/action.yaml
--- a/service-build/spark-build/action.yaml
+++ b/service-build/spark-build/action.yaml
@@ -16,26 +16,26 @@ runs:
   steps:
     - name: Validate Inputs
       run: |
-        error_message=""
+        newline=$'\n'
+        error_message=''
         if [ -z "${{ inputs.ssh_key }}" ]
         then
-          error_message="${error_message}\ssh_key is NULL."
-          error_message="${error_message}\ssh_key description: ${{ inputs.ssh_key.description }}"
+          error_message="${error_message}${newline}ssh_key is NULL."
+          error_message="${error_message}${newline}ssh_key description: ${{ inputs.ssh_key.description }}"
         fi
         if [ -z "${{ inputs.spark_lib_image }}" ]
         then
-          error_message="${error_message}\spark_lib_image is NULL."
-          error_message="${error_message}\spark_lib_image description: ${{ inputs.spark_lib_image.description }}"
+          error_message="${error_message}${newline}spark_lib_image is NULL."
+          error_message="${error_message}${newline}spark_lib_image description: ${{ inputs.spark_lib_image.description }}"
         fi
         if [ -z "${{ inputs.spark_scala_file }}" ]
         then
-          error_message="${error_message}\spark_scala_file is NULL."
-          error_message="${error_message}\spark_scala_file description: ${{ inputs.spark_scala_file.description }}"
+          error_message="${error_message}${newline}spark_scala_file is NULL."
+          error_message="${error_message}${newline}spark_scala_file description: ${{ inputs.spark_scala_file.description }}"
         fi
         if [ ! -z "$error_message" ]
         then
-          echo "$error_message" >/dev/stderr
-          exit 1
+          { echo "$error_message"; exit 1; }
         fi
       shell: bash
     - name: Install SSH Key
