feat: test validator

diff --git a/service-build/spark-build/action.yaml b/service-build/spark-build/action.yaml
--- a/service-build/spark-build/action.yaml
+++ b/service-build/spark-build/action.yaml
@@ -16,6 +16,7 @@ runs:
   steps:
     - name: Validate Inputs
       run: |
+        RED='\033[0;31m'
         newline=$'\n'
         error_message=''
         if [ -z "${{ inputs.ssh_key }}" ]
@@ -35,7 +36,7 @@ runs:
         fi
         if [ ! -z "$error_message" ]
         then
-          { echo "$error_message"; exit 1; }
+          { echo -e "${RED}$error_message"; exit 1; }
         fi
       shell: bash
     - name: Install SSH Key
