feat: testing composite github action

diff --git a/single-workspace/terraform-plan/action.yaml b/single-workspace/terraform-plan/action.yaml
--- a/single-workspace/terraform-plan/action.yaml
+++ b/single-workspace/terraform-plan/action.yaml
@@ -33,6 +33,22 @@ runs:
       uses: hashicorp/setup-terraform@v1.2.1
       with:
         terraform_version: ${{ inputs.terraform-version }}
+    - name: Terraform Format Check
+      id: fmt
+      run: terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?" 
+      #TODO: Uncomment once github supports it
+      #continue-on-error: true
+      shell: bash
+    - name: Post Format
+      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && inputs.enable-plan-commenter == 'true' }}
+      uses: robburger/terraform-pr-commenter@v1.5.0
+      env:
+        GITHUB_TOKEN: ${{ inputs.github-token }}
+        EXPAND_SUMMARY_DETAILS: "false"
+      with:
+        commenter_type: fmt
+        commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
+        commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}
     - name: TF Plan - Initialize
       id: init
       run: |
