fix: refactor

diff --git a/single-workspace-infra/terraform-plan/action.yaml b/single-workspace-infra/terraform-plan/action.yaml
--- a/single-workspace-infra/terraform-plan/action.yaml
+++ b/single-workspace-infra/terraform-plan/action.yaml
@@ -23,20 +23,26 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Set SCRIPT_SOURCE
+      run: |
+        cd /home/runner/work/_actions/GetTerminus/terminus-github-actions/*/shell-scripts
+        dir=$(pwd)
+        echo "SCRIPT_SOURCE=$dir" >> $GITHUB_ENV
+      shell: bash
     - name: Validate Inputs
+      working-directory: ${{ env.SCRIPT_SOURCE }}
       env:
         SSH_KEY: ${{ inputs.ssh_key }}
         TERRAFORM_VERSION: ${{ inputs.terraform_version }}
         GITHUB_TOKEN: ${{ inputs.github_token }}
       run: |
-        cd ${{ github.action_path }}
-        source ../../shell-scripts/input-validator.sh
-        
+        source input-validator.sh
+
         declare -A inputs
         inputs[ssh_key]="$SSH_KEY"
         inputs[terraform_version]="$TERRAFORM_VERSION"
         inputs[github_token]="$GITHUB_TOKEN"
-        
+
         validateInput inputs
       shell: bash
     - name: Install SSH Key
@@ -51,7 +57,7 @@ runs:
         terraform_version: ${{ inputs.terraform_version }}
     - name: Terraform Format Check
       id: fmt
-      run: terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?" 
+      run: terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?"
       #TODO: Uncomment once github supports it
       #continue-on-error: true
       shell: bash
@@ -122,4 +128,3 @@ runs:
         commenter_input: tfplan
         commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
         terraform_version: ${{ inputs.terraform_version }}
-        
