feat: add in datadog synthetics trigger

diff --git a/multi-workspace-infra/terraform-plan/action.yaml b/multi-workspace-infra/terraform-plan/action.yaml
--- a/multi-workspace-infra/terraform-plan/action.yaml
+++ b/multi-workspace-infra/terraform-plan/action.yaml
@@ -160,7 +160,7 @@ runs:
     - name: Get Local Service Name
       id: service_name
       run: |
-        echo "::set-output name=service_name::$(terraform output service_name || echo "::set-output name=service_name::false)"
+        echo "::set-output name=service_name::$(terraform output service_name || echo "false")" || echo "::set-output name=exitcode_continue_on_error::$?"
       shell: bash
 #    - name: Run Datadog Synthetics tests
 #      if: ${{ steps.service_name.outputs.service_name }}
