fix: metaupload test

diff --git a/multi-workspace-infra/terraform-plan/action.yaml b/multi-workspace-infra/terraform-plan/action.yaml
--- a/multi-workspace-infra/terraform-plan/action.yaml
+++ b/multi-workspace-infra/terraform-plan/action.yaml
@@ -36,7 +36,9 @@ runs:
         terraform_version: ${{ inputs.terraform_version }}
     - name: Terraform Format Check
       id: fmt
-      run: terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?" 
+      run: |
+        echo "${*datadog_api*}"
+        terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?" 
       #TODO: Uncomment once github supports it
       #continue-on-error: true
       shell: bash
