fix: validator

diff --git a/multi-workspace-infra/terraform-plan/action.yaml b/multi-workspace-infra/terraform-plan/action.yaml
--- a/multi-workspace-infra/terraform-plan/action.yaml
+++ b/multi-workspace-infra/terraform-plan/action.yaml
@@ -61,104 +61,104 @@ runs:
 #
 #        validateInput inputs
 #      shell: bash
-    - name: Install SSH Key
-      uses: webfactory/ssh-agent@v0.4.1
-      with:
-        ssh-private-key: ${{ inputs.ssh_key }}
-    - name: Pull
-      uses: actions/checkout@v2
-      with:
-        lfs: true
-    - name: Helm Update
-      if: ${{ inputs.artifactory_enabled == 'true' }}
-      run: |
-        helm repo add terminus https://getterminus.jfrog.io/artifactory/default-helm/ --username developer --password ${{ inputs.artifactory_read_access_token }}
-        helm repo update
-        helm dependency update ${{ inputs.artifactory_helm_chart_path }}
-      shell: bash
-    - name: HashiCorp - Setup Terraform
-      uses: hashicorp/setup-terraform@v1.2.1
-      with:
-        terraform_version: ${{ inputs.terraform_version }}
-    - name: Terraform Format Check
-      id: fmt
-      run: |
-        terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?"
-      #TODO: Uncomment once github supports it
-      #continue-on-error: true
-      shell: bash
-    - name: Post TF Format Check
-      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
-      uses: GetTerminus/terraform-pr-commenter@master
-      env:
-        GITHUB_TOKEN: ${{ inputs.github_token }}
-        EXPAND_SUMMARY_DETAILS: "false"
-      with:
-        commenter_type: fmt
-        commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
-        commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}
-        terraform_version: ${{ inputs.terraform_version }}
-    - name: TF Plan - Initialize
-      id: init
-      run: |
-        terraform version
-        terraform init -lock=false -input=false
-      shell: bash
-    - name: Post TF Init Comment
-      # TODO: Add in the below code to all plan commenter if statements when github adds in the functionality
-      # (steps.init.outcome == 'success' || steps.init.outcome == 'failure')
-      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
-      uses: GetTerminus/terraform-pr-commenter@master
-      env:
-        GITHUB_TOKEN: ${{ inputs.github_token }}
-        EXPAND_SUMMARY_DETAILS: "false"
-      with:
-        commenter_type: init
-        commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
-        commenter_exitcode: ${{ steps.init.outputs.exitcode }}
-        terraform_version: ${{ inputs.terraform_version }}
-    - name: TF Plan - Select Workspace
-      if: ${{ inputs.tf_create_workspace != 'true' }}
-      run: |
-        terraform workspace select ${{ inputs.tf_workspace }}
-      shell: bash
-    - name: TF Plan - Create Workspace
-      if: ${{ inputs.tf_create_workspace == 'true' }}
-      run: |
-        terraform workspace new ${{ inputs.tf_workspace }}
-        terraform workspace select ${{ inputs.tf_workspace }}
-      shell: bash
-    - name: TF Plan - Validate
-      id: validate
-      run: |
-        terraform validate
-        terraform workspace show
-      shell: bash
-    - name: Post TF Validate Comment
-      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
-      uses: GetTerminus/terraform-pr-commenter@master
-      env:
-        GITHUB_TOKEN: ${{ inputs.github_token }}
-        EXPAND_SUMMARY_DETAILS: "false"
-      with:
-        commenter_type: validate
-        commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
-        commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
-        terraform_version: ${{ inputs.terraform_version }}
-    - name: TF Plan - Run
-      id: plan
-      run: |
-        terraform plan -var-file=vars/${{ inputs.tf_workspace }}.tfvars -lock=false -input=false -out=tfplan
-      shell: bash
-    - name: Post TF Plan Comment
-      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && inputs.enable_plan_commenter == 'true' }}
-      uses: GetTerminus/terraform-pr-commenter@master
-      env:
-        GITHUB_TOKEN: ${{ inputs.github_token }}
-        EXPAND_SUMMARY_DETAILS: "false"
-        TF_WORKSPACE: ${{ inputs.tf_workspace }}
-      with:
-        commenter_type: plan
-        commenter_input: tfplan
-        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
-        terraform_version: ${{ inputs.terraform_version }}
+#    - name: Install SSH Key
+#      uses: webfactory/ssh-agent@v0.4.1
+#      with:
+#        ssh-private-key: ${{ inputs.ssh_key }}
+#    - name: Pull
+#      uses: actions/checkout@v2
+#      with:
+#        lfs: true
+#    - name: Helm Update
+#      if: ${{ inputs.artifactory_enabled == 'true' }}
+#      run: |
+#        helm repo add terminus https://getterminus.jfrog.io/artifactory/default-helm/ --username developer --password ${{ inputs.artifactory_read_access_token }}
+#        helm repo update
+#        helm dependency update ${{ inputs.artifactory_helm_chart_path }}
+#      shell: bash
+#    - name: HashiCorp - Setup Terraform
+#      uses: hashicorp/setup-terraform@v1.2.1
+#      with:
+#        terraform_version: ${{ inputs.terraform_version }}
+#    - name: Terraform Format Check
+#      id: fmt
+#      run: |
+#        terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?"
+#      #TODO: Uncomment once github supports it
+#      #continue-on-error: true
+#      shell: bash
+#    - name: Post TF Format Check
+#      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
+#      uses: GetTerminus/terraform-pr-commenter@master
+#      env:
+#        GITHUB_TOKEN: ${{ inputs.github_token }}
+#        EXPAND_SUMMARY_DETAILS: "false"
+#      with:
+#        commenter_type: fmt
+#        commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
+#        commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}
+#        terraform_version: ${{ inputs.terraform_version }}
+#    - name: TF Plan - Initialize
+#      id: init
+#      run: |
+#        terraform version
+#        terraform init -lock=false -input=false
+#      shell: bash
+#    - name: Post TF Init Comment
+#      # TODO: Add in the below code to all plan commenter if statements when github adds in the functionality
+#      # (steps.init.outcome == 'success' || steps.init.outcome == 'failure')
+#      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
+#      uses: GetTerminus/terraform-pr-commenter@master
+#      env:
+#        GITHUB_TOKEN: ${{ inputs.github_token }}
+#        EXPAND_SUMMARY_DETAILS: "false"
+#      with:
+#        commenter_type: init
+#        commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
+#        commenter_exitcode: ${{ steps.init.outputs.exitcode }}
+#        terraform_version: ${{ inputs.terraform_version }}
+#    - name: TF Plan - Select Workspace
+#      if: ${{ inputs.tf_create_workspace != 'true' }}
+#      run: |
+#        terraform workspace select ${{ inputs.tf_workspace }}
+#      shell: bash
+#    - name: TF Plan - Create Workspace
+#      if: ${{ inputs.tf_create_workspace == 'true' }}
+#      run: |
+#        terraform workspace new ${{ inputs.tf_workspace }}
+#        terraform workspace select ${{ inputs.tf_workspace }}
+#      shell: bash
+#    - name: TF Plan - Validate
+#      id: validate
+#      run: |
+#        terraform validate
+#        terraform workspace show
+#      shell: bash
+#    - name: Post TF Validate Comment
+#      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
+#      uses: GetTerminus/terraform-pr-commenter@master
+#      env:
+#        GITHUB_TOKEN: ${{ inputs.github_token }}
+#        EXPAND_SUMMARY_DETAILS: "false"
+#      with:
+#        commenter_type: validate
+#        commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
+#        commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
+#        terraform_version: ${{ inputs.terraform_version }}
+#    - name: TF Plan - Run
+#      id: plan
+#      run: |
+#        terraform plan -var-file=vars/${{ inputs.tf_workspace }}.tfvars -lock=false -input=false -out=tfplan
+#      shell: bash
+#    - name: Post TF Plan Comment
+#      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && inputs.enable_plan_commenter == 'true' }}
+#      uses: GetTerminus/terraform-pr-commenter@master
+#      env:
+#        GITHUB_TOKEN: ${{ inputs.github_token }}
+#        EXPAND_SUMMARY_DETAILS: "false"
+#        TF_WORKSPACE: ${{ inputs.tf_workspace }}
+#      with:
+#        commenter_type: plan
+#        commenter_input: tfplan
+#        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
+#        terraform_version: ${{ inputs.terraform_version }}
